"""add Page model

Revision ID: 28ac33cbeede
Revises: 49e425715a2d
Create Date: 2015-01-25 18:04:34.274418

"""

# revision identifiers, used by Alembic.
revision = '28ac33cbeede'
down_revision = '49e425715a2d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day_id', sa.Integer(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('binary', sa.Binary(), nullable=True),
    sa.Column('title', sa.Unicode(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['day_id'], ['day.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('page')
    ### end Alembic commands ###
