#!/usr/bin/env python3

import os
import sys
import json
import glob
import logging
import datetime

import requests
import click
from trogon import tui
from dotenv import load_dotenv
load_dotenv()

from gthnk import Gthnk
from gthnk.model.journal import Journal
from gthnk.filebuffer import FileBuffer


@tui()
@click.group()
def cli():
    pass

@cli.command()
def path():
    "Display the path of the journal filetree"
    g = Gthnk()
    print(g.filetree.get_path())

@cli.command()
def buffer():
    "Display the contents of the file buffers"
    g = Gthnk()
    # parse and accumulate into a blank journal
    j = Journal()
    for buffer in g.buffers:
        fb = FileBuffer(buffer, journal=j)
    print(j)

@cli.command()
@click.option('--date', is_flag=True, default=False, help="Print only the date, not the entry")
@click.option('--previous', is_flag=True, default=False, help="Retrieve the day before the id provided")
@click.option('--next', is_flag=True, default=False, help="Retrieve the day after the id provided")
@click.option('--latest', is_flag=True, default=False, help="Retrieve the latest day")
@click.argument('day_id', default=None, required=False)
def day(date, previous, next, latest, day_id):
    "Retrieve a day from the journal by id (YYYY-MM-DD)"
    g = Gthnk()

    if day_id is None:
        if latest:
            day_id = g.journal.get_latest_day_id()
        else:
            print("Please provide a day id")
            return
    
    day = g.journal.get_day(day_id)
    if day is None:
        print("Day not found")
        return
    
    if previous:
        day = g.journal.get_previous_day(day)
    elif next:
        day = g.journal.get_next_day(day)
    
    if date:
        print(day.day_id)
    else:
        print(day)

@cli.command()
@click.option('--date', is_flag=True, default=False, help="Print only the date")
@click.option('--uri', is_flag=True, default=False, help="Print only the uri")
@click.option('--path', is_flag=True, default=False, help="Print the full file path")
@click.option('--reverse', is_flag=True, default=False, help="Reverse the order of the entries")
@click.option('--count', is_flag=True, default=False, help="Print the number of entries that matched")
@click.option('--num', default=None, help="Number of entries to return")
@click.argument('query', nargs=-1)
def search(date, uri, path, count, num, reverse, query):
    "Search the journal for a query"
    g = Gthnk()

    # # load all days if lazy
    # if g.lazy:
    #     g.filetree.days.load_all()

    query_str = " ".join(query)
    if not query_str:
        print("Please provide a query")
        return

    if num:
        num = int(num)

    if count:
        print(len(list(g.journal.search(query_str))))
        return

    if uri and path:
        print("Cannot provide both --uri and --path at the same time")
        return

    count = 0
    for entry in g.journal.search(query_str, chronological=reverse):
        count += 1
        if date and uri:
            print(entry.day.get_uri())
        elif date and path:
            print(f"{g.filetree.get_path()}/day{entry.day.get_uri()}")
        elif date:
            print(entry.day.day_id)
        elif uri:
            print(entry.get_uri())
        elif path:
            print(f"{g.filetree.get_path()}/entry{entry.get_uri()}")
        else:
            print(entry.render_standalone())
        if num and count >= num:
            break

@cli.command()
@click.argument('gthnk_path')
@click.argument('out_filename', default=None, required=False)
def config(gthnk_path, out_filename):
    "Generate a sample config file, optionally saving to a file"
    secret_key = str(os.urandom(24))
    buf = config_template.format(
        gthnk_path=gthnk_path,
        secret_key=secret_key,
    )

    if out_filename:
        with open(out_filename, "w") as f:
            f.write(buf)
    else:
        print(buf)

@cli.command()
def rotate():
    "Import file buffers and rotate them"
    g = Gthnk()
    g.rotate_buffers()

@cli.command()
@click.argument('filename')
def read(filename):
    "Read a file buffer and import it into the journal"
    g = Gthnk()
    fb = FileBuffer(filename, journal=g.journal)
    g.filetree.write_journal()
    print(f"Journal contains {len(g.journal)} entries")

@cli.command("import")
@click.argument('filename')
def import_artifact(filename):
    "Import filename into the current day, as an artifact"
    g = Gthnk()
    g.filetree.artifacts.import_file(filename)

@cli.command("artifact")
@click.option('--uri', is_flag=True, default=False, help="Print only the uri")
@click.option('--path', is_flag=True, default=False, help="Print the full file path")
@click.option('--load', is_flag=True, default=False, help="Don't be lazy; load artifact")
@click.argument('day_id')
@click.argument('sequence')
def get_artifact(uri, path, load, day_id, sequence):
    "Retrieve an artifact from gthnk"
    g = Gthnk()
    artifact = g.journal.get_artifact(day_id, int(sequence))
    if artifact.filename is None:
        print("Artifact not found")
        return
    if load:
        assert artifact.data

    if uri:
        print(artifact.uri)
    elif path:
        print(artifact.full_filename)
    else:
        print(artifact)


config_template = """
# Gthnk Configuration

INPUT_FILES = "{gthnk_path}/journal.txt"

FILETREE_ROOT="{gthnk_path}"
LAZY = True

LOG_FILENAME = "{gthnk_path}/gthnk.log"
LOG_LEVEL = "INFO"

SECRET_KEY = {secret_key}
BASE_URL = "http://gthnk.lan"
"""


if __name__ == '__main__':
    cli()
