#!/usr/bin/env python3
# gthnk
# Ian Dennis Miller

import os

from flask_script import Manager

from gthnk.__meta__ import __version__
from gthnk_server.server import create_app
from gthnk_server.models.user import User


app = create_app()
manager = Manager(app)


@manager.option('-u', '--username', help='username', required=True)
@manager.option('-p', '--password', help='password', required=True)
def user_add(username, password):
    "add a user to the database"
    User.create_with_password(
        username=username,
        password=password
    )

@manager.option('-u', '--username', help='username', required=True)
def user_del(username):
    "delete a user from the database"
    obj = User.find(username=username)
    if obj:
        obj.delete()
        print("Deleted")
    else:
        print("User not found")

@manager.option('-u', '--username', help='username', required=True)
@manager.option('-p', '--password', help='password', required=True)
def change_password(username, password):
    "change a user password"
    u = User.find(username=username)
    if u:
        u.change_password(password)

@manager.command
def gui():
    """
    drop all databases
    """
    import webview
    webview.create_window('gthnk', 'http://localhost:1620')
    webview.start()

if __name__ == "__main__":
    manager.run()
