#!/usr/bin/env python3

import os
import sys
import json
import glob
import logging
import datetime

import click
from dotenv import load_dotenv
load_dotenv()

from gthnk import Gthnk
from gthnk.filebuffer import FileBuffer


@click.group()
def cli():
    pass

@cli.command()
def path():
    "Display the path of the journal filetree"
    g = Gthnk()
    print(g.filetree.get_path())

@cli.command()
@click.option('--date', is_flag=True, default=False, help="Print only the date")
@click.option('--uri', is_flag=True, default=False, help="Print only the uri")
@click.option('--path', is_flag=True, default=False, help="Print the full file path")
@click.option('--reverse', is_flag=True, default=False, help="Reverse the order of the entries")
@click.option('--count', is_flag=True, default=False, help="Print the number of entries that matched")
@click.option('--num', default=None, help="Number of entries to return")
@click.argument('query', nargs=-1)
def search(date, uri, path, count, num, reverse, query):
    "Search the journal for a query"
    g = Gthnk()

    # # load all days if lazy
    # if g.lazy:
    #     g.filetree.load_all_days()

    query_str = " ".join(query)
    if not query_str:
        print("Please provide a query")
        return

    if num:
        num = int(num)

    if count:
        print(len(list(g.journal.search(query_str))))
        return

    if uri and path:
        print("Cannot provide both --uri and --path at the same time")
        return

    count = 0
    for entry in g.journal.search(query_str, chronological=reverse):
        count += 1
        if date and uri:
            print(entry.day.get_uri())
        elif date and path:
            print(f"{g.filetree.get_path()}/day{entry.day.get_uri()}")
        elif date:
            print(entry.day.day_id)
        elif uri:
            print(entry.get_uri())
        elif path:
            print(f"{g.filetree.get_path()}/entry{entry.get_uri()}")
        else:
            print(entry.render_standalone())
        if num and count >= num:
            break

@cli.command()
@click.argument('path')
@click.argument('filename', default=None, required=False)
def config(path, filename):
    "Create a config file"
    secret_key = str(os.urandom(24))
    buf = config_template.format(
        gthnk_path=path,
        secret_key=secret_key,
    )

    if filename:
        with open(out_file, "w") as f:
            f.write(buf)
    else:
        print(buf)

@cli.command()
def rotate():
    "Import file buffers and rotate them"
    g = Gthnk()
    g.rotate_buffers()

@cli.command()
@click.argument('filename')
def read(filename):
    "Read a file buffer and import it into the journal"
    g = Gthnk()
    fb = FileBuffer(filename, journal=g.journal)
    g.filetree.write_journal()
    print(g.journal)


config_template = """
# Gthnk Configuration

INPUT_FILES = "{gthnk_path}/journal.txt"

LAZY=true
BACKEND=filetree
FILETREE_ROOT="{gthnk_path}"

LOG_FILENAME="{gthnk_path}/gthnk.log"
LOG_LEVEL = "INFO"

SECRET_KEY = {secret_key}
BASE_URL = "http://gthnk.lan"
SQLALCHEMY_DATABASE_URI = "sqlite:///{gthnk_path}/gthnk.db"
SQLALCHEMY_TRACK_MODIFICATIONS = False
"""


if __name__ == '__main__':
    cli()
