"""add ItemList

Revision ID: 49e425715a2d
Revises: 53c0a83b0b70
Create Date: 2014-11-22 13:36:35.670935

"""

# revision identifiers, used by Alembic.
revision = '49e425715a2d'
down_revision = '53c0a83b0b70'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=256), nullable=True),
    sa.Column('content', sa.Unicode(length=4294967296), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_list')
    ### end Alembic commands ###
