"""tracking page file extension

Revision ID: fe4bd690134
Revises: e4aca3e83ef
Create Date: 2015-01-30 19:10:39.056260

"""

# revision identifiers, used by Alembic.
revision = 'fe4bd690134'
down_revision = 'e4aca3e83ef'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page', sa.Column('extension', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('page', 'extension')
    ### end Alembic commands ###
