# Gthnk
# docker-compose.yaml
# inspired by https://stackoverflow.com/a/48611098
version: "3.3"
services:
  gthnk-server:
    image: iandennismiller/gthnk
    container_name: gthnk-server
    volumes:
      - ~/.gthnk:/home/gthnk/.gthnk
      # - ~/Dropbox/gthnk:/home/gthnk/.gthnk
      # - ~/Seafile/gthnk:/home/gthnk/.gthnk
    networks:
      - gthnk-net
    ports:
      - "1620:1620"
    environment:
      - TZ=America/Toronto
    command: sudo -i -u gthnk sh -c 'gthnk-firstrun.sh /home/gthnk/.gthnk; gthnk-server.sh'

  gthnk-rotate:
    image: docker:edge
    container_name: gthnk-rotate
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - gthnk-net
    # This image does not support time zones and is always in UTC.
    # You must set the cron job to execute at a sensible time relative to your local time zone.
    # For Eastern (America/Toronto) use 5 AM UTC to ensure post-midnight run, which is: 0 5 * * * 
    command: >
      sh -c "
      echo '0 5 * * * docker exec gthnk-server sudo -i -u gthnk gthnk-rotate.sh' > /etc/crontabs/root
      && crond -f"

networks:
  gthnk-net:
